### ISSUE TITLE
java worker api(put, call ) perf problem 

### ISSUE THREAD

**Issue by songqing** [ant-tech-alliance/ray#43]
### Describe the problem

Now, I am doing perf test about plasma queue, and I compare it with original method(like `put` in java worker), but I find when calling `put` many times continuously, it will become slower and slower. The test is as below.

![image](https://user-images.githubusercontent.com/9260628/42269483-d7dcf36a-7fb0-11e8-8ae4-52cfb969202d.png)

and the output is as below.

![image](https://user-images.githubusercontent.com/9260628/42268867-36eb059c-7faf-11e8-847f-f5d56023c738.png)

Besides, the problem occurs when calling `Ray.call` many times continuously.
and in python worker, the problem doesn't occur.

I have tried to find the cause.
 When using test in arrow/java/plasma https://github.com/eric-jj/arrow/blob/147ae2f05bb0be8d646ce4ad15f73e7909ca24b2/java/plasma/src/test/java/org/apache/arrow/plasma/PlasmaClientTest.java#L175 , the problem doesn't appear. 
I also remove the java serialization and use a simple byte[] instead, it seems serialization is not relevant.

In fact, it's fast enough when testing in arrow/java/plasma, and it's also fast enough when testing in java worker without `objectStoreProxy.put(objectId, obj, metadata);`, but it's slow when putting the two together.

So what's the reason?

**Comment by songqing** [comment]
@salah-man please help to have a look.

**Comment by songqing** [comment]
@raulchen It seems `arrow.plasma.PlasmaClientJNI.create` costs most of the time.


![image](https://user-images.githubusercontent.com/9260628/42274376-048c9556-7fbf-11e8-84bd-8ccfd9d36387.png)

**Comment by raulchen** [comment]
@songqing nice find.
I just read the code (https://github.com/apache/arrow/blob/master/cpp/src/plasma/lib/java/org_apache_arrow_plasma_PlasmaClientJNI.cc#L84), the JNI layer seems to be just a thin wrapper around the C++ client. I didn't find anything wrong there. You may want to @salah-man, who wrote that code, or continue profiling the C++ code.

**Comment by songqing** [comment]
@raulchen In fact, I found a place that may be relevant, see https://www.jianshu.com/p/451cc865d413.
`arrow.plasma.PlasmaClientJNI.create` use `DirectByteBuffer ` to init a `ByteBuffer` instead of `HeapByteBuffer `, and `DirectByteBuffer ` costs more time than `HeapByteBuffer ` when allocating a new buffer.

**Comment by raulchen** [comment]
The problem described in that article should be irrelevant. What it measures is the time of **creating direct byte buffer (allocating off-heap memory)**. While in our case, `PlasmaClientJNI.create` doesn't allocate memory. It just uses the DirectByteBuffer as a view of the shared memory.

**Comment by songqing** [comment]
@raulchen OK, but `arrow.plasma.PlasmaClientJNI.create` has no other method costing much time except `  Status s = client->Create(oid, size, md, md_size, &data);` which is the cpp method also used in python worker and doesn't cost much time.

**Comment by zhijunfu** [comment]
@songqing You might want to profile the plasma store and see where the CPU cycles are spent. In my original test, store's CPU usage is very high compared to python case.

**Comment by mylinyuzhi** [comment]
in the gitlab branch, i test i in mac-air with jvm args: 
```
-XX:+PrintGCDetails  -XX:+PrintGCDateStamps -Xmx500M -Xmn500M
```
the perf is:

put obj:0:726
put obj:10000:15207
put obj:20000:11167
put obj:30000:8011
put obj:40000:9047
put obj:50000:8230
put obj:60000:7647
put obj:70000:8610
put obj:80000:8173
put obj:90000:7280

that is ok

**Comment by raulchen** [comment]
@songqing yeah, that's also what I was wondering...

@zhijunfu interesting. If that is true, it'd be very surprising to me. Do you have any theory what would make a difference between Python and Java? I think to the store, everything is just bytes.

**Comment by zhijunfu** [comment]
@raulchen yes this does seem strange.. I don't have a plausible theory at the moment. 
thanks @mylinyuzhi , nice to know that it doesn't appear in gitlab. one step closer to the root cause.

**Comment by songqing** [comment]
@mylinyuzhi Yes, I tested it's OK in gitlab ray, and arrow's code in gitlab is the same as in github, so there's something wrong with my github ray code.

**Comment by songqing** [comment]
@raulchen @mylinyuzhi I find ray.config.ini is relevant. Before I set`object_store_occupied_memory_MB = 200` as I plan to push lots of obj, and now I change the option back to `object_store_occupied_memory_MB = 200`, now the putting time doesn't increase always, see following.

put obj: 0: 83
put obj: 10000: 4507
put obj: 20000: 14009
put obj: 30000: 32463
put obj: 40000: 42322
put obj: 50000: 14017
put obj: 60000: 30005
put obj: 70000: 40472
put obj: 80000: 12000
put obj: 90000: 28032

but the time increases periodic.

Besides gitlab ray only cost 2000ms while github cost 20000ms average in the same statition.

**Comment by songqing** [comment]
This problem has been solved, see https://github.com/apache/arrow/pull/2220
